### ISSUE TITLE
Not working on Firefox

### ISSUE THREAD

**Issue by oskarski** [ArekSredzki/top-control#1]
You can use document.querySelector(selector) instead of document.body.  Selector is html on firefox. Elsewhere it's body

**Comment by eldilor** [comment]
You can use document.querySelector(selector) instead of document.body.  Selector is html on firefox. Elsewhere it's body

**Comment by ArekSredzki** [comment]
Thanks or the tip! Mind submitting a PR?

**Comment by ArekSredzki** [comment]
Fixed in #2
